font_family Px437 DOS/V re. JPN30
font_size 17

#font_family Iosevka Term Light
#font_size 14.0

bold_font auto
italic_font auto
bold_italic_font auto

#background_opacity 0.9
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Corvine
include current-theme.conf
# END_KITTY_THEME
